---
version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    # networks:
    #   - my_network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # image: backend:latest
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/payments
    # networks:
    #   - my_network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    # networks:
    #   - my_network


volumes:
  mongo_data:
    # driver: local