apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 72.6.3
    helm:
      releaseName: prometheus
      values: |
        fullnameOverride: prometheus-grafana
        namespaceOverride: monitoring
        crds:
          enabled: true  # ✅ This line tells Helm to install CRDs
        grafana:
          adminPassword: prom-operator
          defaultDashboardsEnabled: true
          service:
            type: ClusterIP
          ingress:
            enabled: true
            annotations:
              nginx.ingress.kubernetes.io/rewrite-target: /
            hosts:
              - grafana.localhost
            paths:
              - /
            pathType: Prefix
            
        prometheus:
          prometheusSpec:
            serviceMonitorSelector:
              matchLabels:
                app: payment-service
            serviceMonitorNamespaceSelector:
              matchNames:
                - payment-service
            resources:
              requests:
                memory: 400Mi
                cpu: 100m
              limits:
                memory: 600Mi
                cpu: 200m
        alertmanager:
          enabled: true
          alertmanagerSpec:
            replicas: 1
        nodeExporter:
          enabled: true
        kubeStateMetrics:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true  # ✅ Enables better handling of CRDs
      # - ApplyOutOfSyncOnly=true
