apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 72.6.3  # or use latest stable
    helm:
      releaseName: prometheus
      values: |
        grafana:
          adminPassword: prom-operator
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
    # Optional: Customize values.yaml as needed
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
