apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/namespace.yml
  - base/mongo-secret.yml
  - base/backend/deployment.yml
  - base/backend/service.yml
  - base/frontend/deployment.yml
  - base/frontend/service.yml
  - base/mongo/deployment.yml
  - base/mongo/service.yml
  - base/mongo/configmap.yml
  - base/ingress.yml
