apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-script
  namespace: payment-service
data:
  init-mongo.js: |
    db.createUser({
      user: process.env.MONGO_INITDB_ROOT_USERNAME,
      pwd: process.env.MONGO_INITDB_ROOT_PASSWORD,
      roles: [
        {
          role: "readWrite",
          db: "payments"
        }
      ]
    });