---
name:  Citizen Payment Service CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      registry: docker.io
      backend_image: saikanth9010/payment-service-backend
      frontend_image: saikanth9010/payment-service-frontend
      backend_context: ./backend
      frontend_context: ./frontend
      TAG: ${{ github.sha }}
      TAG1: latest
    

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build backend image
      run: |
        docker build -t $backend_image:$TAG -t $backend_image:$TAG1 $backend_context

    - name: Push backend image
      run: |
        docker push $backend_image:$TAG
        docker push $backend_image:$TAG1

    - name: Build frontend image 
      run: |
        docker build -t $frontend_image:$TAG -t $frontend_image:$TAG1 $frontend_context

    - name: Push frontend image
      run: |
        docker push $frontend_image:$TAG
        docker push $frontend_image:$TAG1
